In [2]:
import numpy as np

In [3]:
# 打印numpy库的版本
print(np.__version__)

2.2.6


In [4]:
# 构造全零矩阵,并打印
z = np.zeros([4,4])
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
# 创建一个10-49的数组，并且倒叙排序
z = np.arange(10,50,1)
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [6]:
# 找到一个数组中不为零0的索引
print(np.nonzero(z))

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39]),)


In [7]:
# 随即构造一个3*3的矩阵
z = np.random.random([3,3])
print(z.min())
print(z.max())

0.05727267802767899
0.9470363399645856


In [8]:
# 构造一个5*5矩阵，令其内部值为1，最外部值为0
z = np.ones((5,5))
z = np.pad(z, pad_width = 1, constant_values = 0, mode = "constant")
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [9]:
# 构建一个shape为（6，7，8）的矩阵，并找到第100个的元素的索引值
z = np.random.random([6,7,8])
print(z[np.unravel_index(100,(6,7,8))])

0.1818319557072846


In [10]:
# 对一个5*5矩阵进行归一化操作 归一化 (当前值 - 最小值) / (最大值 - 最小值)
z = np.random.random([5, 5])
z_max = z.max()
z_min = z.min()
z = (z - z_min) / (z_max - z_min)
print(z)

[[0.51824944 0.87558034 0.17538391 0.6630944  0.67282231]
 [0.9800482  0.53800184 0.22104617 0.08677504 1.        ]
 [0.02675895 0.57686031 0.41438499 0.0945338  0.48096557]
 [0.22043859 0.80802219 0.23191255 0.08648615 0.27941664]
 [0.97876172 0.         0.03138794 0.09827135 0.89516582]]


In [ ]:
z1 = np.random.randint(0,10,20)
z2 = np.random.randint(0,10,20)
print('z1:' + str(z1))
print('z2:' + str(z2))
print('same value:' + str(np.intersect1d(z1, z2)))

z1:[1 0 4 2 1 6 6 1 6 0 8 0 1 7 2 5 0 3 0 0]
z1:[1 0 4 2 1 6 6 1 6 0 8 0 1 7 2 5 0 3 0 0]
same value:[0 1 2 3 4 5 7 8]


In [12]:
# 得到一个数的整数部分
z = np.random.uniform(0, 10, 10)
print(z)
print(np.floor(z))

[0.53118437 1.45579382 0.94279378 1.79651032 9.03529714 2.39729493
 2.61316241 7.28316279 3.49579051 9.43021402]
[0. 1. 0. 1. 9. 2. 2. 7. 3. 9.]


In [ ]:
# 打印数据的部分值
z = np.random.randint(0,10,100)